### PR TITLE
[TASK] added remove by url method

### PR DESCRIPTION
**Pull request by sandermangel**
I've used this myself as a feature before, would like to add it

### CODE REVIEW

**Comment by digitalpianism** [comment]
@sandermangel well it's a default Magento feature right ? https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Page/Block/Template/Links.php#L162

**Comment by digitalpianism** [comment]
@sandermangel Except if you want the module to absolutely be compatible with Magento < 1.3.0 ^^

**Comment by sandermangel** [comment]
@digitalpianism ok ok, good point. added also a bugfix. happy now? :P

**Comment by digitalpianism** [comment]
done, Imma just add a comment to specify it's for Magento < 1.3.0 ^^

**Comment by sandermangel** [comment]
thanks!

**Comment by digitalpianism** [comment]
@sandermangel I changed the method name to reflect the OG Magento method https://github.com/digitalpianism/easytoplinks/commit/24eb67978a88ccaf13ad5852493998df1e76a84e#diff-c30bfdd82252e6c64446534bd22ce99eL60

**Pull request merged**
